class ROLE(object):
    OWNER = 10
    ADMIN = 5
    STANDARD = 0


class ERROR_CODE():
    APP_NOT_FIND = 0
    NOT_HAVE_APP = 1
    USER_NOT_FIND = 2
    TOBJECT_NOT_FIND = 3
    UNABLE_TO_DECRYPT = 4
    USER_NOT_MATCH = 5
    PLATFORM_KEY_EXPIRED = 6
